### PR TITLE
Websocket close

### PR DESCRIPTION
**Pull request by relu91**
This pull request adds closing methods to client side API. It' a trivial change but it's important to free the underlying resources. 

I just want to point out that the close method in web socket client is asynchronous and when the connection is actually closed the method onBrokenSocket() of the user handler is called.  Should we add a specific onClose method? Or a simple javadoc warning about this would be enough?

### CODE REVIEW

**Comment by fr4ncidir** [comment]
Secondo me basta onBrokenSocket e un po' di javadoc

**Comment by lroffia** [comment]
Ciao Cris, why do we need a clone method? From my point of view the API should support the following: UPDATE, query, SUBSCRIBE, UNSUBSCRIBE. During subscribe the websocket is open and a "subscribe message" is sent. As the save websocket can be used for multiple requests, during unsubscribe an "unsubscribe" message is sent. If this is the last one, so the websocket can also be closed. Why do you want to introduce a Close method?

**Comment by relu91** [comment]
Ciao Luca! Glad to here your feedback here! I actually thought about your proposed when I first tackle this problem. I choose this one for the following reasons:

1. *It introduces complexity*. You have to keep track of every new subscription and count down when you receive an UNSUBSCRIBE message.
2. *It violates the Single Responsability Principle at method level*. The unsubscribe method has not trivial side effects. 
3. *httpclient should be closed*. It cannot be closed after the last UNSUBSCRIBE because the client could still do UPDATES or QUERIES.
4. *it's not compatibile with try-with-resources*. I consider this as a plus of my solution.

Plus closing resources it's a well-known method to deal with system resources. Finally if you are concerned about API interface cleanness (the api should only have UPDATE, query, SUBSCRIBE, UNSUBSCRIBE ), you can put those method in a java interface and let the class implement that. 

**Notice** this is actually a good idea so we divide implementation from interface. if you are ok I'll to also this change ASAP!

**Comment by lroffia** [comment]
Ciao Cris, please find my comments below:

> Il giorno 15 nov 2017, alle ore 19:15, Cristiano Aguzzi <notifications@github.com> ha scritto:
> 
> Ciao Luca! Glad to here your feedback here! I actually thought about your proposed when I first tackle this problem. I choose this one for the following reasons:
> 
> It introduces complexity. You have to keep track of every new subscription and count down when you receive an UNSUBSCRIBE message.
Complexity? It is a simple counter…I guess...
> It violates the Single Responsability Principle at method level. The unsubscribe method has not trivial side effects.
The effect I guess is clear: it unsubscribes and if it is the last opened subscriptions it also closes the socket.
> httpclient should be closed. It cannot be closed after the last UNSUBSCRIBE because the client could still do UPDATES or QUERIES.
Http is different from WebSocket. HttpClient should close correctly. If not, this is an issue and has to be fixed.
> it's not compatibile with try-with-resources. I consider this as a plus of my solution.
> Plus closing resources it's a well-known method to deal with system resources. Finally if you are concerned about API interface cleanness (the api should only have UPDATE, query, SUBSCRIBE, UNSUBSCRIBE ), you can put those method in a java interface and let the class implement that.
> 
> Notice this is actually a good idea so we divide implementation from interface. if you are ok I'll to also this change ASAP
> 
> 

Maybe I am wrong or I am missing something…please let me know in both cases. Thank you!

**Comment by relu91** [comment]
> Maybe I am wrong or I am missing something…please let me know in both cases.

I think it's more a matter of tastes, neither of the two solution it's wrong. But here two things that I want to clarify:

>it unsubscribes and if it is the last opened subscriptions it also closes the socket
This sentence is the exact effect of the violation of the SRP. You are using multiple sentences (... **and** ...) to describe the effect of a function. Here it is a simple one: it unsubscribes. 

 >Http is different from WebSocket. HttpClient should close correctly. If not, this is an issue and has to be fixed.

Yeah it's different but in this case you should close the client. Read [here at 1.2.2 chapter](http://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html) and also [here](https://stackoverflow.com/questions/21574478/what-is-the-difference-between-closeablehttpclient-and-httpclient-in-apache-http). So since to close this you should add a close method we can close also websockets. 

>it's not compatibile with try-with-resources. I consider this as a plus of my solution.
 Plus closing resources it's a well-known method to deal with system resources. Finally if you are concerned about API interface cleanness (the api should only have UPDATE, query, SUBSCRIBE, UNSUBSCRIBE ), you can put those method in a java interface and let the class implement that.

Also I think this is still a good point.

p.s.

 >Complexity? It is a simple counter…I guess...

Complexity is complexity 😄 , more time to understand the code, more code to maintain etc.. I know it's ridiculous but why use a counter when we don't need one?

**Comment by lroffia** [comment]
> Il giorno 15 nov 2017, alle ore 20:01, Cristiano Aguzzi <notifications@github.com> ha scritto:
> 
> Yeah it's different but in this case you should close the client. Read here at 1.2.2 chapter <http://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html> and also here <https://stackoverflow.com/questions/21574478/what-is-the-difference-between-closeablehttpclient-and-httpclient-in-apache-http>. So since to close this you should add a close method we can close also websockets.


I forget to close the client and so this is an issue. We just need to correct the following:

SPARQL11SEProtocol.java

383:		} finally {
			try {
				response.close();
			httpclient.close();
			} catch (IOException e) {
				return new ErrorResponse(500, e.getMessage());
			}
		}

I am still not convinced we need a close method :-). The counter is fine I guess (developers also do not need to know about that. They just call unsubscribe). Otherwise, the developer needs to call the close method. To close what? Remember that subscriptions have to be closed if needed, but in my opinion this is not so frequent (in particular in IoT: a consumer is subscribed because it needs to receive notification to do its job). If a client leaves, the subscriptions are closed.

Maybe we need a F2F meeting to better understand each other :-)

**Comment by relu91** [comment]
```java
} finally {
			try {
				response.close();
			httpclient.close();
			} catch (IOException e) {
				return new ErrorResponse(500, e.getMessage());
			}
		}
```
If you close the httpclient in every update and query method, you also must create the httpclient in every call.  

About developer point of view, it's common sense to know that protocols and communication api need to be freed after use. It's like http, you need to close the response after you read from it. For example when I was developing the SEPA-GO api I was wondering where the resources were freed in java api and I started to search about this close methods. 

@fr4ncidir @desmovalvo  what do you think? I'd like to close this pull request ASAP.   

> Maybe we need a F2F meeting to better understand each other :-)

yeah sure!!! 😃 still IMHO is better to move on since it's a trivial change.

**Comment by relu91** [comment]
There's also a pratical example were you need a close method to better handle the memory/computational ratio. 

Assuming you are a constrained device where a connection with websocket is considered high computational demanding. You want to unsubscribe for a certain time and then subscribe again ( i.e. you don't want to be interrupted because you need to handle some important task ). If you close in unsubscribe, the developer won't be able to leave the connection open and then subscribe again with minimum computational effort.

I see your point that this behavior it's like to expose implementation details to user, but not quite... since instead websocket you could use every other protocol.

**Comment by lroffia** [comment]
So do we need also an “open” method?

**Comment by lroffia** [comment]
> Il giorno 16 nov 2017, alle ore 10:09, Cristiano Aguzzi <notifications@github.com> ha scritto:
> 
> } finally {
> 			try {
> 				response.close();
> 			httpclient.close();
> 			} catch (IOException e) {
> 				return new ErrorResponse(500, e.getMessage());
> 			}
> 		}
> If you close the httpclient in every update and query method, you also must create the httpclient in every call.
> 
> 

This is exactly how is done now. Otherwise, we can change this by creating the client on “open” (like a join) and close it on “close” (like live). I would prefer to create and dispose the client on each call.

**Comment by relu91** [comment]
>This is exactly how is done now. Otherwise, we can change this by creating the client on “open” (like a >join) and close it on “close” (like live). I would prefer to create and dispose the client on each call.

No, it's not. The client is created here: `final CloseableHttpClient httpClient = HttpClients.createDefault();` in the class static constructor. Then in the method:
```java
public Response update(UpdateRequest req, int timeout) {
		StringEntity requestEntity = null;

		CloseableHttpResponse httpResponse = null;
		HttpEntity responseEntity = null;
		int responseCode = 0;
		String responseBody = null;

		try {
			// Set request entity
			if (properties.getUpdateMethod().equals(HTTPMethod.URL_ENCODED_POST)) {
				requestEntity = new StringEntity("update=" + URLEncoder.encode(req.getSPARQL(), "UTF-8"));
			} else if (properties.getUpdateMethod().equals(HTTPMethod.POST)) {
				requestEntity = new StringEntity(req.getSPARQL(), Consts.UTF_8);
			}
			updatePostRequest.setEntity(requestEntity);
			RequestConfig requestConfig = RequestConfig.custom().setSocketTimeout(timeout).setConnectTimeout(timeout)
					.build();
			updatePostRequest.setConfig(requestConfig);

			// Execute HTTP request
			logger.debug("Execute SPARQL 1.1 QUERY (timeout: " +timeout+ " ms) "+updatePostRequest.toString(),timeout);
			long timing = System.nanoTime();
			httpResponse = httpClient.execute(updatePostRequest);
			timing = System.nanoTime() - timing;
			logger.debug("UPDATE_TIME (" + timing / 1000000 + " ms)");

			// Status code
			responseCode = httpResponse.getStatusLine().getStatusCode();

			// Body
			responseEntity = httpResponse.getEntity();
			responseBody = EntityUtils.toString(responseEntity, Charset.forName("UTF-8"));
			EntityUtils.consume(responseEntity);

		} catch (IOException e) {
			return new ErrorResponse(req.getToken(), HttpStatus.SC_INTERNAL_SERVER_ERROR, e.getMessage());
		} finally {
			try {
				if (httpResponse != null)
					httpResponse.close();
			} catch (IOException e) {
				return new ErrorResponse(req.getToken(), HttpStatus.SC_INTERNAL_SERVER_ERROR, e.getMessage());
			}

			requestEntity = null;
			responseEntity = null;
		}

		if (responseCode >= 400) {
			try {
				return new ErrorResponse(req.getToken(), new JsonParser().parse(responseBody).getAsJsonObject());
			} catch (JsonParseException e) {
				return new ErrorResponse(req.getToken(), responseCode, responseBody);
			}
		}

		return new UpdateResponse(req.getToken(), responseBody);
```

I don't see were you are creating it. I'm thinking about the open method, it's quite logic to add it but I'm not quite sure. Otherwise I agree with this:

>Otherwise, we can change this by creating the client on “open” (like a join) and close it on “close” (like >live). I would prefer to create and dispose the client on each call.

**Comment by relu91** [comment]
I think that the open method is not needed, like in the [CloseableHttpClient](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/CloseableHttpClient.html) there's no open method and also in InputStreams and other similar classes. 

About the close we could create two different classes that have different behavior one capable of auto-realeasing resources and the other like this implementation.

**Pull request merged**
